services:
  strapi:
    build: 
      context: ./src/backend
    ports:
      - "1337:1337"
    # volumes:
    #   - ./src/backend:/app
    environment:
    - DATABASE_CLIENT=postgres
    - DATABASE_NAME=strapi
    - DATABASE_HOST=postgres
    - DATABASE_PORT=5432
    - DATABASE_USERNAME=strapi
    - DATABASE_PASSWORD=strapi
    - NODE_ENV=development
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - strapi-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: zaq1@WSX
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  strapi-data:
  pgadmin-data:
